import React from 'react';
import { JournalEntry, formatJournalTime, getMomentEmoji } from '@/lib/journal';
import { getCloneAvatar } from '@/lib/dialogue';

interface JournalFeedProps {
  entries: JournalEntry[];
  onDeleteEntry?: (entryId: string) => void;
}

export default function JournalFeed({ entries, onDeleteEntry }: JournalFeedProps) {
  if (entries.length === 0) {
    return (
      <div className="journal-empty">
        <div className="empty-icon">📔</div>
        <h3>No Journal Entries Yet</h3>
        <p>Your clones will start journaling once they begin their travels. Make sure to set their personality first!</p>
      </div>
    );
  }

  // Sort entries by timestamp (newest first)
  const sortedEntries = [...entries].sort((a, b) => b.timestamp - a.timestamp);

  return (
    <div className="journal-feed">
      {sortedEntries.map((entry, index) => {
        const avatar = getCloneAvatar(entry.destination);
        const momentEmoji = getMomentEmoji(entry.moment);
        const timeAgo = formatJournalTime(entry.timestamp);

        return (
          <div
            key={entry.id}
            className="journal-entry"
            style={{ animationDelay: `${Math.min(index * 0.05, 1)}s` }}
          >
            <div className="entry-header">
              <div className="entry-avatar">{avatar}</div>
              <div className="entry-meta">
                <div className="entry-title">
                  <span className="clone-name">{entry.cloneName}</span>
                  <span className="moment-badge">
                    {momentEmoji} {entry.moment.replace('-', ' ')}
                  </span>
                </div>
                <div className="entry-location">
                  📍 {entry.destination}
                  <span className="entry-time">{timeAgo}</span>
                </div>
              </div>
              <div className="entry-actions">
                <span className="ai-model-badge" title={`Generated by ${entry.aiModel === 'claude' ? 'Claude' : 'ChatGPT'}`}>
                  {entry.aiModel === 'claude' ? '🤖' : '💬'}
                </span>
                {onDeleteEntry && (
                  <button
                    onClick={() => onDeleteEntry(entry.id)}
                    className="btn-icon delete-btn"
                    title="Delete entry"
                  >
                    🗑️
                  </button>
                )}
              </div>
            </div>

            <div className="entry-content">
              <p className="entry-message">{entry.message}</p>
            </div>

            <div className="entry-footer">
              <div className="entry-timestamp">
                {new Date(entry.timestamp).toLocaleString()}
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
